name: "P6 GHA: Builds a NextJS Static Site"
description: "P6 GHA: Builds a NextJS Static Site"
author: "Philip M. Gollucci"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.0
    - name: Node
      uses: p6m7g8-actions/node-setup@main
    - name: Disable Next.js Telemetry
      shell: bash
      run: echo "NEXT_TELEMETRY_DISABLED=1" >> "$GITHUB_ENV"
    - name: Run build
      shell: bash
      run: pnpm run build
